---
title: "FinalProject"
author: "Lin Zuo, Lab Section 1"
mainfont: Times Roman
documentclass: article
fontsize: 12pt
output:
  pdf_document: default
---
```{r}
library(dplyr)
library(car)
library(ggplot2)
library(lattice)
library(arm)
library(pROC)
```

#cleaned dataset in excel before the analysis
```{r}
edu = read.csv("FinalProject.csv", header = T)
edu$month = as.numeric(sapply(as.character(edu$date),function(x){strsplit(x,"/")[[1]][1]}))
edu$month = as.factor(edu$month)#no linear trend among different months, so treat it as a categorical variable
edu$season[edu$month==1|edu$month==11|edu$month==12]="winter"
edu$season[edu$month==2|edu$month==3|edu$month==4]="spring"
edu$season[edu$month==5|edu$month==6|edu$month==7]="summer"
edu$season[edu$month==8|edu$month==9|edu$month==10]="fall"
edu$area[edu$area == "CS"] = "STEM"
#cases under each month vary, so lump together several levels together by define a new variable: season
edu = edu%>%filter(hour_certified!=0)
```

##What kind of classes drew most participants?
```{r}
#use institution, area, honor, season and hour_certified as predictors to model participants
#participant
hist(edu$participant, main = paste("Histogram of number of participants"), xlab = "number of participants" ) #skewed, so log transformation
edu$logparticipant = log(edu$participant)
hist(edu$logparticipant, main = paste("Histogram of log number of participants"), xlab = "log number of participants") #now it looks good
##EDA
boxplot(logparticipant ~ institution, data=edu) #insitution should be included
boxplot(logparticipant ~ area, data = edu) #area should be included
boxplot(logparticipant ~ honor, data = edu) #honor should be included
boxplot(logparticipant ~ season, data = edu) #season should be included
plot(y=edu$logparticipant, x=edu$hour_certified, main = paste("logparticipants VS hour_certified"), xlab = "hour_certified", ylab = "log participants") # the distribution of the predictor is skewed, so log hour_certified
edu$loghour_certified = log(edu$hour_certified)
plot(y=edu$logparticipant, x=edu$loghour_certified, main = paste("logparticipants VS log hour_certified"), xlab = "log hour_certified", ylab = "log participants") #try linear trend

#fit model
parnumreg1 = lm(participant ~ institution + area + honor + month + hour_certified, data = edu)
summary(parnumreg1)#full model
BIC(parnumreg1)
parnumreg2 = lm(participant ~ institution + area + honor + month, data = edu)
summary(parnumreg2)#kick out hour_certified because of low p value
BIC(parnumreg2)
anova(parnumreg1, parnumreg2)#large p value, so keep with the small model
#try logy -> much better
parnumreg3 = lm(logparticipant ~ institution + area + honor + month + hour_certified, data = edu)
summary(parnumreg3)
BIC(parnumreg3) #model 3 is way better than model 1
#try log hour_certified
parnumreg4 = lm(logparticipant ~ institution + area + honor + month + loghour_certified, data = edu)
summary(parnumreg4)
BIC(parnumreg4) #higher than model 3, but let's check assumptions
plot(y=parnumreg3$residuals, x=edu$hour_certified)
abline(0,0)
plot(y=parnumreg4$residuals, x=edu$loghour_certified) 
abline(0,0)
#model 3 doesn't meet the assumptions, go with the log one/model 4
parnumreg4_sea = lm(logparticipant ~ institution + area + honor + season + loghour_certified, data = edu)
summary(parnumreg4_sea)
BIC(parnumreg4_sea) #using season instead of month improves BIC; so go with parnumreg4_sea
parnumreg5 = lm(logparticipant ~ area + honor + season + loghour_certified, data = edu)
summary(parnumreg5)
anova(parnumreg4_sea, parnumreg5) #no need for institution; go with the model 5
BIC(parnumreg5) #goes lower, which is good, so now with the model 5
parnumreg6 = lm(logparticipant ~ area + honor + loghour_certified, data = edu)
summary(parnumreg6)
anova(parnumreg4_sea,parnumreg6) #keep season in the model
BIC(parnumreg6) #lowest BIC value
parnumreg7 = lm(logparticipant ~ area + honor, data = edu)
summary(parnumreg7)
anova(parnumreg7, parnumreg5) #loghour_certified is important
parnumreg8 = lm(logparticipant ~ honor + loghour_certified, data = edu)
anova(parnumreg8, parnumreg5) #area is important
parnumreg9 = lm(logparticipant ~ area + loghour_certified, data=edu)
anova(parnumreg9, parnumreg5) #honor is also important
#so far, I have landed on the parnumreg5: logparticipant ~ area + honor + season + loghour_certified
#let's check assumptions for each predictor
#check assumptions with the boxplot, mean should be similar and close to 0, variance are pretty similar between categories, and each category meets the normality assumption
boxplot(parnumreg5$residuals ~ edu$area) #not bad
boxplot(parnumreg5$residuals ~ edu$honor) #not very suspicious
boxplot(parnumreg5$residuals ~ edu$season) #looks good
plot(parnumreg5$residuals ~ edu$loghour_certified) #scattered randomly
#investigate interaction effects
bwplot(participant ~ area | honor, data=edu) #maybe interaction
xyplot(participant ~ loghour_certified | honor, data=edu) #maybe
xyplot(participant ~ loghour_certified | area, data=edu) #not really
parnumreg10 = lm(logparticipant ~ area * honor + loghour_certified, data = edu)
summary(parnumreg10)
anova(parnumreg10, parnumreg6) #honor*area doesn't matter
parnumreg13 = lm(logparticipant ~ area + honor*loghour_certified, data = edu)
summary(parnumreg13)
anova(parnumreg13, parnumreg6) #honor*loghour_certified doesn't matter
par = lm(logparticipant ~ honor+area* loghour_certified, data = edu)
anova(par, parnumreg6)
par13 = lm(logparticipant ~ area+ honor*loghour_certified, data = edu)
anova(par13, parnumreg6)


#check residuals
boxplot(par$residuals ~ edu$area) #not bad
boxplot(par$residuals ~ edu$honor) #not very suspicious
boxplot(par$residuals ~ edu$season) #looks good
plot(par$residuals ~ edu$loghour_certified)
abline(0,0)

boxplot(parnumreg4_sea$residuals ~ edu$area) #not bad
boxplot(parnumreg4_sea$residuals ~ edu$honor) #not very suspicious
boxplot(parnumreg4_sea$residuals ~ edu$season) #looks good
boxplot(parnumreg4_sea$residuals ~ edu$institution)
plot(parnumreg4_sea$residuals ~ edu$loghour_certified)
abline(0,0)
```
My final model is logparticipant ~  honor+area*season + loghour_certified (model12)

##What percentage of those participants stay and become certified?
```{r}
fin = read.csv("edu2.csv", header = T)
fin = fin%>%filter(hour_certified!=0)
fin$perc_cert = fin$certified/fin$participant
fin$month = as.numeric(sapply(as.character(fin$date),function(x){strsplit(x,"/")[[1]][1]}))
fin$month = as.factor(fin$month)
fin$season[fin$month==1|fin$month==11|fin$month==12]="winter"
fin$season[fin$month==2|fin$month==3|fin$month==4]="spring"
fin$season[fin$month==5|fin$month==6|fin$month==7]="summer"
fin$season[fin$month==8|fin$month==9|fin$month==10]="fall"

#EDA
tapply(fin$perc_cert, fin$institution, mean)
table(fin$institution) 
tapply(fin$perc_cert, fin$area, mean)
table(fin$area)
tapply(fin$perc_cert, fin$season, mean)
table(fin$season)
plot(x=fin$hour_certified, y=fin$perc_cert, main=paste("percentage of certified VS hour_certified"), xlab = "hour_certified", ylab = "percentage of certified")#hour_certified needs a quadratic term
#some possible transformations
fin$hour_certified_2 = (fin$hour_certified)^2
fin$log_hour_certified = log(fin$hour_certified)
fin$hour_certified_inverse = 1/fin$hour_certified
#interaction effects
xyplot(perc_cert ~ hour_certified | area, data = fin)
xyplot(perc_cert ~ hour_certified | institution, data = fin)
#model
finreg1 = glm(perc_cert~institution + area + hour_certified, family=binomial,weights=fin$participant,data=fin)
summary(finreg1)
fin = glm(perc_cert~season + institution + area + hour_certified, family=binomial,weights=fin$participant,data=fin)
summary(finreg1)
anova(finreg1, fin, test = "Chisq")

rawresid1 = fin$perc_cert - fitted(finreg1)
#model checking for categorical variables
tapply(rawresid7, fin$institution, mean)
table(fin$institution) 
tapply(rawresid7, fin$area, mean)
table(fin$area)
#model checking for continuous variables
plot(fin$hour_certified, rawresid7, main = paste("residual plot for hour_certified"), xlab = "hour_certified", ylab="residual")
plot(fin$perc_cert, fitted(finreg1)) #there's problem fitting high perc_cert with small hour_certified
##so I tried a bunch of transformations with hour_certified
#I added quadratic term
finreg2 = glm(perc_cert~institution + area + hour_certified + hour_certified_2, family=binomial,weights=fin$participant,data=fin)
summary(finreg2)
rawresid2 = fin$perc_cert - fitted(finreg2)
plot(fin$hour_certified, rawresid2, main = paste("residual plot for hour_certified"), xlab = "hour_certified with the squared term", ylab="residual")
plot(fitted(finreg2), fin$perc_cert)
#I did the log transformation
finreg3 = glm(perc_cert~institution + area + log_hour_certified, family=binomial,weights=fin$participant,data=fin)
summary(finreg3)
rawresid3 = fin$perc_cert - fitted(finreg3)
plot(fin$hour_certified, rawresid3, main = paste("residual plot for log hour_certified"), xlab = "log hour_certified", ylab="residual")
plot(fitted(finreg3), fin$perc_cert)
#I used the inverse version of hour_certified
finreg4 = glm(perc_cert~institution + area + hour_certified_inverse, family=binomial,weights=fin$participant,data=fin)
summary(finreg4)
rawresid4 = fin$perc_cert - fitted(finreg4)
plot(fin$hour_certified, rawresid4, main = paste("residual plot for inverse hour_certified"), xlab = "inverse hour_certified", ylab="residual")
plot(fitted(finreg4), fin$perc_cert)
#they improved little, so I looked specifically at those points that haven't been fit well
#add interaction effects
finreg5 = glm(perc_cert~institution + area * hour_certified, family=binomial,weights=fin$participant,data=fin)
rawresid5 = fin$perc_cert - fitted(finreg5)
plot(fin$hour_certified, rawresid5)
plot(fitted(finreg5), fin$perc_cert)
anova(finreg5, finreg1, test ="Chisq")
finreg6 = glm(perc_cert~institution*hour_certified+area, family=binomial,weights=fin$participant,data=fin)
anova(finreg6, finreg1, test = "Chisq")
rawresid6 = fin$perc_cert - fitted(finreg6)
plot(fin$hour_certified, rawresid6)
plot(fitted(finreg6), fin$perc_cert)
finreg7 = glm(perc_cert~(institution+area)*hour_certified, family=binomial,weights=fin$participant,data=fin)
anova(finreg7, finreg6, test = "Chisq")
anova(finreg7, finreg5, test = "Chisq")
rawresid7 = fin$perc_cert - fitted(finreg7)
plot(fin$hour_certified, rawresid7)
plot(fitted(finreg7), fin$perc_cert)


finreg8 = glm(perc_cert~(institution+area)*log_hour_certified, family=binomial,weights=fin$participant,data=fin)
rawresid8 = fin$perc_cert - fitted(finreg8)
plot(fin$hour_certified, rawresid8)
plot(fitted(finreg8), fin$perc_cert)
finreg9 = glm(perc_cert~(institution+area)*(hour_certified+hour_certified_2), family=binomial,weights=fin$participant,data=fin)
rawresid9 = fin$perc_cert - fitted(finreg9)
plot(fin$hour_certified, rawresid9)
plot(fitted(finreg9), fin$perc_cert)
#although the model 8 and 9 perform better in terms of modeling and BIC, they are hard in terms of interpretation, so I go with model 7 and do the interpretation
```
